version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    container_name: sales_agent
    build:
      context: .
    image: event-planner-api:latest
    env_file:
      - .env
    volumes:
#      - ./app:/app
      - .:/app
    command: python app/app.py
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PYTHONPATH: /app/app
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app_network

  chroma:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8001"
    networks:
      - app_network
    volumes:
      - chroma_data:/var/lib/chroma


volumes:
  postgres_data:
  chroma_data:

networks:
  app_network:
    driver: bridge
