"""Add reviews, products, categories, companies, topics, marketplaces

Revision ID: 8c4aae5662bd
Revises: 7c5aa55450cd
Create Date: 2024-09-09 18:45:11.755467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '8c4aae5662bd'
down_revision: Union[str, None] = '7c5aa55450cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


sentiment_enum = ENUM('Positive', 'Negative', name='sentimentenum', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    sentiment_enum.create(op.get_bind())

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplaces_id'), 'marketplaces', ['id'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('review_topics',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('review_id', 'topic_id')
    )
    op.add_column('reviews', sa.Column('review_date', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('sentiment', sentiment_enum, nullable=False))
    op.add_column('reviews', sa.Column('marketplace_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('company_id', sa.Integer(), nullable=False))
    op.alter_column('reviews', 'text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.drop_index('ix_reviews_text', table_name='reviews')
    op.drop_index('ix_reviews_username', table_name='reviews')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'marketplaces', ['marketplace_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'companies', ['company_id'], ['id'])
    op.drop_column('reviews', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_index('ix_reviews_username', 'reviews', ['username'], unique=False)
    op.create_index('ix_reviews_text', 'reviews', ['text'], unique=False)
    op.alter_column('reviews', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('reviews', 'company_id')
    op.drop_column('reviews', 'marketplace_id')
    op.drop_column('reviews', 'sentiment')
    op.drop_column('reviews', 'product_id')
    op.drop_column('reviews', 'review_date')
    op.drop_table('review_topics')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_marketplaces_id'), table_name='marketplaces')
    op.drop_table('marketplaces')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
